# network/kb/network_deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: network-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: network
  template:
    metadata:
      labels:
        app: network
    spec:
      containers:
        - name: network-container
          image: localhost/network-module:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: network-config
          env:
            - name: NETWORK_KEY
              valueFrom:
                secretKeyRef:
                  name: network-secret
                  key: network_key
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: network-secret
                  key: discord_token
            - name: NOVELAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: network-secret
                  key: novelai_api_key
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
